services:
  - type: web
    name: team-sorting-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python team_splitter.py
    envVars:
      - key: FLASK_ENV
        value: production